apiVersion: v1
kind: Service
metadata:
  name: {{ include "authms-optima.fullname" . }}-svc
  labels:
    {{- include "authms-optima.labels" . | nindent 4 }}
spec:
  type: {{ .Values.auth.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.auth.service.port }}
      targetPort: {{ .Values.auth.service.targetPort }}
      name: auth-svc
  selector:
    {{- include "authms-optima.selectorLabels" . | nindent 4 }}
