apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authms-optima.fullname" . }}
  labels:
    {{- include "authms-optima.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "authms-optima.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.auth.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "authms-optima.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.auth.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.auth.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.auth.nameOverride }}
          securityContext:
            {{- toYaml .Values.auth.securityContext | nindent 12 }}
          image: "{{ .Values.auth.image.repository }}/{{ .Values.auth.image.name }}:{{ .Values.auth.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          ports:
            - name: auth-svc
              containerPort: {{ .Values.auth.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.auth.service.port }}
            initialDelaySeconds: {{ .Values.auth.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.auth.probes.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.auth.service.port }}
            initialDelaySeconds: {{ .Values.auth.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.auth.probes.periodSeconds }} 
          resources:
            {{- toYaml .Values.auth.resources | nindent 12 }}
      {{- with .Values.auth.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.auth.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.auth.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
