apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "budget-optima.fullname" . }}
  labels:
    {{- include "budget-optima.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "budget-optima.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "budget-optima.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.budget.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.budget.image.repository }}:{{ .Values.budget.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.budget.image.imagePullPolicy }}
          ports:
            - name: {{ .Values.budget.service.name }}
              containerPort: {{ .Values.budget.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/info
              port: {{ .Values.budget.service.port }}
            initialDelaySeconds: {{ .Values.probes.springservice.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.springservice.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /actuator/info
              port: {{ .Values.budget.service.port }}
            initialDelaySeconds: {{ .Values.probes.springservice.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.springservice.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
