apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dbms-optima.fullname" . }}
  labels:
    {{- include "dbms-optima.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dbms-optima.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.db.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "dbms-optima.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.db.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.db.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.db.nameOverride }}
          securityContext:
            {{- toYaml .Values.db.securityContext | nindent 12 }}
          image: "{{ .Values.db.image.repository }}/{{ .Values.db.image.name }}:{{ .Values.db.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          ports:
            - name: db-svc
              containerPort: {{ .Values.db.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.db.service.port }}
            initialDelaySeconds: {{ .Values.db.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.db.probes.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.db.service.port }}
            initialDelaySeconds: {{ .Values.db.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.db.probes.periodSeconds }} 
          resources:
            {{- toYaml .Values.db.resources | nindent 12 }}
      {{- with .Values.db.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
