apiVersion: v1
kind: Service
metadata:
  name: {{ include "mortgage-optima.fullname" . }}-svc
  labels:
    {{- include "mortgage-optima.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mortgage.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.mortgage.service.port }}
      targetPort: {{ .Values.mortgage.service.targetPort }}
      name: mortgage-svc
  selector:
    {{- include "mortgage-optima.selectorLabels" . | nindent 4 }}
