apiVersion: v1
kind: Service
metadata:
  name: {{ include "payout-optima.fullname" . }}-svc
  labels:
    {{- include "payout-optima.labels" . | nindent 4 }}
spec:
  type: {{ .Values.payout.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.payout.service.port }}
      targetPort: {{ .Values.payout.service.targetPort }}
      name: payout-svc
  selector:
    {{- include "payout-optima.selectorLabels" . | nindent 4 }}
