apiVersion: v1
kind: Service
metadata:
  name: {{ include "poolingfund-optima.fullname" . }}-svc
  labels:
    {{- include "poolingfund-optima.labels" . | nindent 4 }}
spec:
  type: {{ .Values.poolingFund.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.poolingFund.service.port }}
      targetPort: {{ .Values.poolingFund.service.targetPort }}
      name: poolingfund-svc
  selector:
    {{- include "poolingfund-optima.selectorLabels" . | nindent 4 }}

