apiVersion: v1
kind: Service
metadata:
  name: {{ include "portingfund-optima.fullname" . }}-svc
  labels:
    {{- include "portingfund-optima.labels" . | nindent 4 }}
spec:
  type: {{ .Values.portingFund.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.portingFund.service.port }}
      targetPort: {{ .Values.portingFund.service.targetPort }}
      name: portingfund-svc
  selector:
    {{- include "portingfund-optima.selectorLabels" . | nindent 4 }}


